---
- hosts: web
  become: yes
  gather_facts: false
  tasks:
    - name: Change the working directory to somedir/ before executing the command.
      shell: Welcome.sh >> somelog.txt
      args:
        chdir: ~/home/test/
