---
- hosts: dev
  become: yes
  gather_facts: false
  tasks:
    - name: Ansible play for vars
      yum:
        name: "{{ application_name }}"
        state: "{{ state }}"
        
        
# command to run this playbook ansible-playbook test.yml --extra-vars "application_name=tree state=present" 
